output_path: "./output"

views:
    - 'View_001'
    - 'View_003'
    - 'View_004'
    - 'View_005'
    - 'View_006'
    - 'View_007'
    - 'View_008'
configs:
    View_001: "./config/config_singleview_PETS2009S2L1_View_001.yaml"
    View_003: "./config/config_singleview_PETS2009S2L1_View_003.yaml"
    View_004: "./config/config_singleview_PETS2009S2L1_View_004.yaml"
    View_005: "./config/config_singleview_PETS2009S2L1_View_005.yaml"
    View_006: "./config/config_singleview_PETS2009S2L1_View_006.yaml"
    View_007: "./config/config_singleview_PETS2009S2L1_View_007.yaml"
    View_008: "./config/config_singleview_PETS2009S2L1_View_008.yaml"

feeder: 
    name: 'FeederPETS2009S2L1'
    FeederPETS2009S2L1:
        start: 0
        end: 794
        object_class: 'pedestrian'
        th_score: 0.75
        histograms:
            enable: true
            bins: 255
            channels: [0,1,2]
        bboxes:
            enable: true
    
calibration: "./calibration.json"
    
matching:
    threads: 24
    max_distance: 25
    distance_none: 50
    n_candidates: 3
    n_min_views_clique: 3
    verbose: false
    
tracking:
    batch_size: 50
    
    # a trajectory is considered completed if it has not been updated for this time/frames
    completed_after: 30
    access_points: "./overlapping_fov/overlapping_fov_n3.json"

    detections:
        weight_source_sink: 3
        max_jump: 4
        verbose: true
        weight_distance:       
            sigma_distance: 500
            sigma_jump: 4
            sigma_color_histogram: 0.1
            sigma_box_size: 0.1
            max_distance: 1000
            use_color_histogram: false
            use_bbox: false
        weight_confidence:
            mul: 0
            bias: 0

    tracklets: 
        weight_source_sink: 0.1
        max_jump: 20
        length_endpoints: 5
        verbose: true
        weight_distance:
            sigma_color_histogram: 0.3
            sigma_motion: 2000
            alpha: 0.2
            cutoff_motion: 0.1
            cutoff_appearance: 0.1
            use_color_histogram: true
        weight_confidence:
            mul: 0
            # if it is not bigger than weight_source_sink you may lose tracklets
            bias: 0.11    